name: cuckoo
description: "Cuckoo - HKU Moodle Tracker"
publish_to: 'none'
version: 2.0.1+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  persistent_bottom_nav_bar: ^5.0.2
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  path_provider: ^2.1.3
  flutter_local_notifications: ^17.0.1
  flutter_native_splash: ^2.4.0
  font_awesome_flutter: ^10.7.0
  connectivity_plus: ^6.0.3
  toggle_switch: ^2.3.0
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.2.6
  uni_links: ^0.5.1
  fluttertoast: ^8.2.5
  dio: ^5.4.2
  json_annotation: ^4.8.1
  collection: ^1.18.0
  sticky_headers: ^0.3.0+2
  intl: ^0.19.0
  material_symbols_icons: ^4.2719.3
  flutter_html: ^3.0.0-beta.2
  async: ^2.11.0
  cached_network_image: ^3.3.1
  auto_size_text: ^3.0.0
  flutter_timezone: ^1.0.8
  timezone: ^0.9.3
  html: ^0.15.4
  open_filex: ^4.4.0
  table_calendar: ^3.1.1
  package_info_plus: ^8.0.0
  in_app_purchase: ^3.2.0
  device_info_plus: ^10.1.0
  flutter_animate: ^4.5.0
  flutter_colorpicker: ^1.1.0
  background_fetch: ^1.3.5

dev_dependencies:
  json_model: ^1.0.0
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: fonts/Inter-Black.ttf
          weight: 900
  assets:
    - images/illus/
    - images/illus/dark/
    - images/splash/